[package]
name = "cdda_editor"
version = "0.1.0"
authors = ["Fox Box <foxboxpdx@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.41"
clap = { version = "3.1.12", features = ["derive"] }